language: node_js
node_js: stable
verbose: true

cache:
  directories:
    - node_modules

scripts: 
  - npm run build

after_success:
  - git config --global user.name "pacific-legal-portal"
  - git remote rm origin
  - git remote add origin https://pacific-legal-portal:${GITHUB_TOKEN}@github.com/pacific-legal-portal/pacific-legal-lsat.git
  - npm run deploy